---
mattermost:
  build: .
  links:
  - db
  ports:
  - 80:8080
  restart: always
  environment:
    SQL_DATASOURCE: "root:ch4ngeIt@tcp(db:3306)/gitlabhq?charset=utf8mb4,utf8"
    EMAIL_SENDPUSHNOTIFICATIONS:  "true"
    EMAIL_PUSHNOTIFICATIONSERVER: "https://push-test.mattermost.com"

db:
  image: percona
  mem_limit: 512m
  environment:
    MYSQL_ROOT_PASSWORD: ch4ngeIt
    MYSQL_DATABASE: gitlabhq
